# -*- coding: utf-8 -*-
"""Image Preproccesing Functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11iV3t5tO4mU4x2SWTMmzlrMeA9OcqNSG
"""

import cv2
from PIL import Image
import numpy as np

def Image_Processing_main(file_path: str):
  try:
    # Open the image file using OpenCV
    img_original = cv2.imread(file_path)
    if img_original is None:
        raise FileNotFoundError(f"Image not loaded: {file_path}")

    print(f"Successfully opened image: {file_path}")


    # Apply contrast enhancement (uses original uint8 image)
    img_enhanced = Image_contrased_enhancemend(img_original)

    img_denoised= remove_noise(img_enhanced)

    # Convert to LAB color space (uses original uint8 image)
    img_lab = Image_convertion_Lab(img_denoised)

    # Convert to HSV color space (uses original uint8 image)
    img_hsv = Image_convertion_HSV(img_denoised)

    # Rescale the image for operations that might need 0-1 float values
    # The original img_original (uint8) is preserved for cv2.cvtColor operations
    img_rescaled_RGB = Image_rescaling(img_denoised)
    img_rescaled_lab = Image_rescaling(img_denoised)
    img_rescaled_hsz = Image_rescaling(img_denoised)
    print("Image processing steps completed successfully.")
    return img_original, img_rescaled, img_enhanced, img_lab, img_hsv

  except FileNotFoundError:
    print(f'Error: File not found or could not be loaded at {file_path}')
  except Exception as e:
    print(f'An error occurred: {e}')

__all__ = ["Image_Processing_main"]






def Image_rescaling(img_object):
  # Convert the image object to a NumPy array if it's a PIL Image, otherwise assume it's already a NumPy array
  if isinstance(img_object, Image.Image):
    img_array = np.array(img_object)
  else: # Assume it's already a numpy array (from cv2.imread)
    img_array = img_object

  #print(f'Original image shape for rescaling: {img_array.shape}')
  #print(f'Original image data type for rescaling: {img_array.dtype}')

  # Check if the data type is integer and has a max value (e.g., 255 for 8-bit)
  if np.issubdtype(img_array.dtype, np.integer) and img_array.max() > 1:
    # Assuming 8-bit images (0-255 range), rescale to 0-1 float
    rescaled_array = img_array / 255.0
    #print(f'Rescaled image data type: {rescaled_array.dtype}')
    return rescaled_array
  else:
    # If already float or scaled, return as is (or handle as needed)
    #print('Image data type is not integer 0-255, skipping rescaling or already rescaled.')
    return img_array

def Image_contrased_enhancemend(img_object):
  # img_object should be uint8 here
  img_Lab = cv2.cvtColor(img_object, cv2.COLOR_RGB2LAB)
  l, a, b = cv2.split(img_Lab)
  clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
  l_clahe = clahe.apply(l)
  img_Lab_clahe = cv2.merge([l_clahe, a, b]) # Corrected: cv2.merge expects a list/tuple
  img_enhanced = cv2.cvtColor(img_Lab_clahe, cv2.COLOR_LAB2RGB) # Corrected: COLOR_LAB_BG2BGR -> COLOR_LAB2BGR
  return img_enhanced

def Image_convertion_Lab(img_object):
  img_Lab = cv2.cvtColor(img_object, cv2.COLOR_RGB2LAB)
  return img_Lab

def Image_convertion_HSV(img_object):
  img_HSV = cv2.cvtColor(img_object, cv2.COLOR_RGB2HSV)
  return img_HSV # Added return statement

def remove_noise(img, method="bilateral"):
  if img is None:
        raise ValueError("Image not found or invalid path")

    # Apply the selected method
  if method == "gaussian":
        denoised = cv2.GaussianBlur(img, (5, 5), 0)

  elif method == "median":
        denoised = cv2.medianBlur(img, 5)

  elif method == "bilateral":
        # Bilateral filter preserves edges while removing noise
        denoised = cv2.bilateralFilter(img, d=9, sigmaColor=75, sigmaSpace=75)

  elif method == "fastNlMeans":
        # Powerful non-local means denoising
        denoised = cv2.fastNlMeansDenoisingColored(img, None, h=10, hColor=10, templateWindowSize=7, searchWindowSize=21)

  else:
        raise ValueError("Invalid method. Choose from: 'gaussian', 'median', 'bilateral', 'fastNlMeans'.")

  return denoised

# Example usage with an actual image file:
image_file_path = '/root/.cache/kagglehub/datasets/akhatova/pcb-defects/versions/1/PCB_DATASET/images/Mouse_bite/08_mouse_bite_04.jpg'
img_original, img_rescaled, img_enhanced, img_lab, img_hsv = Image_Processing_main(image_file_path)

"""Please choose an actual image file path from the output above to use with the `Image_Processing_main` function."""
